"""
ReportLab PDF generation for India Stock Analyzer research notes.
Returns PDF as bytes so Streamlit can stream it as a download.
"""
from __future__ import annotations

import io
from datetime import date
from typing import Optional

from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER, TA_LEFT, TA_RIGHT
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import cm
from reportlab.platypus import (
    BaseDocTemplate,
    Frame,
    HRFlowable,
    PageTemplate,
    Paragraph,
    Spacer,
    Table,
    TableStyle,
)


# ---------------------------------------------------------------------------
# Colours & brand
# ---------------------------------------------------------------------------

BRAND_BLUE = colors.HexColor("#0D47A1")
BRAND_ACCENT = colors.HexColor("#1976D2")
LIGHT_GREY = colors.HexColor("#F5F5F5")
MID_GREY = colors.HexColor("#9E9E9E")
TEXT_DARK = colors.HexColor("#212121")
GREEN = colors.HexColor("#2E7D32")
RED = colors.HexColor("#C62828")


# ---------------------------------------------------------------------------
# Page layout callbacks
# ---------------------------------------------------------------------------

def _header_footer(canvas, doc):
    """Draw branded header and footer on every page."""
    canvas.saveState()
    width, height = A4

    # Header bar
    canvas.setFillColor(BRAND_BLUE)
    canvas.rect(0, height - 2 * cm, width, 2 * cm, fill=1, stroke=0)
    canvas.setFillColor(colors.white)
    canvas.setFont("Helvetica-Bold", 14)
    canvas.drawString(1.5 * cm, height - 1.2 * cm, "India Stock Analyzer")
    canvas.setFont("Helvetica", 9)
    canvas.drawRightString(width - 1.5 * cm, height - 1.2 * cm, f"Research Note | {date.today():%d %b %Y}")

    # Footer
    canvas.setFillColor(MID_GREY)
    canvas.setFont("Helvetica", 7)
    disclaimer = (
        "DISCLAIMER: This report is generated by an AI system for informational purposes only. "
        "It does not constitute investment advice. Past performance is not indicative of future results. "
        "Please consult a SEBI-registered investment advisor before making investment decisions."
    )
    canvas.drawCentredString(width / 2, 0.8 * cm, disclaimer)
    canvas.setFont("Helvetica", 8)
    canvas.drawRightString(width - 1.5 * cm, 0.8 * cm, f"Page {doc.page}")

    canvas.restoreState()


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------

def build_pdf(morning_note: str, stock_data: dict) -> bytes:
    """
    Generate a branded PDF research note.

    Args:
        morning_note: Full AI-generated morning note text (markdown-like).
        stock_data:   dict from core/fetcher.get_stock_info().

    Returns:
        PDF content as bytes for Streamlit download_button.
    """
    buf = io.BytesIO()
    styles = getSampleStyleSheet()

    # Custom styles
    title_style = ParagraphStyle(
        "Title", parent=styles["Title"],
        textColor=BRAND_BLUE, fontSize=18, spaceAfter=6,
    )
    h2_style = ParagraphStyle(
        "H2", parent=styles["Heading2"],
        textColor=BRAND_ACCENT, fontSize=12, spaceBefore=12, spaceAfter=4,
    )
    body_style = ParagraphStyle(
        "Body", parent=styles["Normal"],
        fontSize=9, leading=14, textColor=TEXT_DARK,
    )
    label_style = ParagraphStyle(
        "Label", parent=styles["Normal"],
        fontSize=8, textColor=MID_GREY,
    )

    # Document setup with custom page template
    doc = BaseDocTemplate(
        buf,
        pagesize=A4,
        leftMargin=1.5 * cm,
        rightMargin=1.5 * cm,
        topMargin=3 * cm,
        bottomMargin=2 * cm,
    )
    frame = Frame(
        doc.leftMargin, doc.bottomMargin,
        doc.width, doc.height,
        id="main",
    )
    doc.addPageTemplates([PageTemplate(id="main", frames=[frame], onPage=_header_footer)])

    story = []

    # --- Stock title ---
    name = stock_data.get("longName", stock_data.get("ticker", "Unknown"))
    ticker = stock_data.get("ticker", "")
    price = stock_data.get("currentPrice", "N/A")
    chg = stock_data.get("changePercent", 0)
    chg_str = f"{chg:+.2f}%" if isinstance(chg, (int, float)) else "N/A"

    story.append(Paragraph(f"{name} ({ticker})", title_style))
    story.append(Paragraph(f"₹{price}  {chg_str}  |  {date.today():%d %B %Y}", label_style))
    story.append(HRFlowable(width="100%", thickness=1, color=BRAND_BLUE, spaceAfter=8))

    # --- Fundamentals table ---
    story.append(Paragraph("Key Fundamentals", h2_style))

    def fmt(v, pct=False, prefix=""):
        if v is None:
            return "N/A"
        try:
            fv = float(v)
            if pct:
                return f"{fv*100:.1f}%"
            return f"{prefix}{fv:,.2f}"
        except Exception:
            return str(v)

    mcap_cr = round((stock_data.get("marketCap") or 0) / 1e7, 0)
    table_data = [
        ["Metric", "Value", "Metric", "Value"],
        ["P/E (Trailing)", fmt(stock_data.get("trailingPE")),
         "P/E (Forward)", fmt(stock_data.get("forwardPE"))],
        ["EPS (₹)", fmt(stock_data.get("trailingEps"), prefix="₹"),
         "Price/Book", fmt(stock_data.get("priceToBook"))],
        ["Market Cap", f"₹{mcap_cr:,.0f} Cr",
         "Beta", fmt(stock_data.get("beta"))],
        ["Div. Yield", fmt(stock_data.get("dividendYield"), pct=True),
         "ROE", fmt(stock_data.get("returnOnEquity"), pct=True)],
        ["Op. Margin", fmt(stock_data.get("operatingMargins"), pct=True),
         "Net Margin", fmt(stock_data.get("profitMargins"), pct=True)],
        ["52-Wk High", fmt(stock_data.get("fiftyTwoWeekHigh"), prefix="₹"),
         "52-Wk Low", fmt(stock_data.get("fiftyTwoWeekLow"), prefix="₹")],
    ]

    col_widths = [doc.width * 0.28, doc.width * 0.22, doc.width * 0.28, doc.width * 0.22]
    tbl = Table(table_data, colWidths=col_widths)
    tbl.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), BRAND_BLUE),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("FONTSIZE", (0, 0), (-1, -1), 8),
        ("BACKGROUND", (0, 1), (-1, -1), LIGHT_GREY),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, LIGHT_GREY]),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.lightgrey),
        ("FONTNAME", (0, 1), (0, -1), "Helvetica-Bold"),
        ("FONTNAME", (2, 1), (2, -1), "Helvetica-Bold"),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ("TOPPADDING", (0, 0), (-1, -1), 4),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
    ]))
    story.append(tbl)
    story.append(Spacer(1, 0.4 * cm))

    # --- Morning note body ---
    story.append(Paragraph("AI-Generated Research Note", h2_style))
    story.append(HRFlowable(width="100%", thickness=0.5, color=BRAND_ACCENT, spaceAfter=6))

    # Convert markdown-ish text to ReportLab paragraphs
    for line in morning_note.split("\n"):
        stripped = line.strip()
        if not stripped:
            story.append(Spacer(1, 0.2 * cm))
            continue
        if stripped.startswith("## "):
            story.append(Paragraph(stripped[3:], h2_style))
        elif stripped.startswith("# "):
            story.append(Paragraph(stripped[2:], h2_style))
        elif stripped.startswith("- ") or stripped.startswith("• "):
            story.append(Paragraph(f"• {stripped[2:]}", body_style))
        elif stripped.startswith("**") and stripped.endswith("**"):
            bold_style = ParagraphStyle("Bold", parent=body_style, fontName="Helvetica-Bold")
            story.append(Paragraph(stripped[2:-2], bold_style))
        else:
            # Replace inline ** bold ** markers
            cleaned = stripped.replace("**", "")
            story.append(Paragraph(cleaned, body_style))

    story.append(Spacer(1, 0.5 * cm))

    doc.build(story)
    return buf.getvalue()
